### ISSUE TITLE
Hi Druuka

### ISSUE THREAD

**Issue by jazzvivi2** [Druuka/LightHack#1]
Hi, as I see you have experience with the ETC project using UDP instead of the serial port. I am trying to build a wifi one but I have a problem of continuous reset, if you have time could you take a look at this?
Thank you!

https://community.etcconnect.com/etclabs/f/lighthack/33286/lighthack-wifi/103293#103293

**Comment by Druuka** [comment]
Hello,

I have done many different OSC devices that interact with the Eos family.  I have done a few wireless ones but they were not based on the esp line.  I used the particle dev boards.  I’ve been meaning to play with the esp32 wifi and get some of that side working as well.  The network version of Osc is a bit different than the usb one for most purposes.  I will see if I can come up with a basic working example and post it to my GitHub.  

I will take a deeper look at the forum discussion on this one.  I have been reading it a little but haven’t had time to get involved.

Thanks,

Andrew

**Comment by jazzvivi2** [comment]
Thanks for your time!
