### ISSUE TITLE
Motorised faders

### ISSUE THREAD

**Issue by cameronaffleck** [Druuka/LightHack#3]
Hi Andrew,
I've been having a look at trying to incorporate motorised faders into a networked fader wing, so that the fader wing can be remote to the desk. I've been having a look at your Sub37withFeedback code to try and understand it and adapt it for my own project. Do you have a diagram of how you wired up your particular fader?
Do you think that https://www.robotshop.com/uk/motorized-10k-linear-slide-pot.html would be a suitable fader to try this with? I'd eventually end up with 5 motorised faders, with 0.96" OLED displays above them and the appropriate Go/Stop buttons below them. 
Any suggestions for this would be greatly appreciated!
Thanks
Cam

**Comment by cameronaffleck** [comment]
Or, alternatively, this fader? https://www.reichelt.com/gb/en/alps-rs60n-studio-fader-motor-and-touch-sense-5k-rs60n11m9-lin5k-p73883.html?PROVID=2788&gclid=CjwKCAjwkPX0BRBKEiwA7THxiPSN7Ib7B3jwEoOccuUt2UmEdk2aQlwNJrkbjeY6mWQY6eb2kA8coBoChtUQAvD_BwE&&r=1
This one is actually 4v-10v
Thanks for your thoughts

**Comment by Druuka** [comment]
The first fader should work.  I just finished a project recently that had two motorized faders, two buttons, and a display.  I will get that code up on my GitHub site soon.

Andrew

**Comment by cameronaffleck** [comment]
Is the new project network based? I’ve had difficulty finding a library that successfully encodes the OSC data via TCP. EOS reports packet corruption with even the smallest OSC string.

**Comment by Druuka** [comment]
Current project is network based but uses udp not tcp.  I’m working on a tcp library but it is not finished yet
Currently with eos you can specify several udp destinations

Thanks. 

Andrew
